### ISSUE TITLE
是不是有几个地方需要改进

### ISSUE THREAD

**Issue by xingzuhui** [snltty/cmonitor#1]
1.服务端是网页的，但是一般控制的情况，不可能让所有人改动，所以没必要nodejs和vue做成http前端。wpf 基于netcore8就好。在服务器端主控。 用户使用考虑的是情景，不是炫技。
2.被控端不要基于.net framwork4 做东西了，要基于netcore 6 或8，不过你要是担心系统运行没最新的.net平台，你发布的时候连运行环境一起发布，反正win8以后都可以安装。
3.linux系统上的客户端你是不是完全重新写的，据我了解的，netcore是支持linux安装的，所以就直接编写一个就行，窗口我不知道怎么办，但是社区好像有linux、mac上运行wpf的包，所以可以达到一次代码、各端运行。

**Comment by snltty** [comment]
1. 有几个考虑，1、现在我使用的更多场景是使用手机查看监控。2、wpf或winform无法进行裁剪，单文件发布会很大，更多PC会带有netframework而不是netcore。3、如果喜欢客户端形式，可以扩展
2. 被控端主程序基于netcore，单文件发布，窗口程序（壁纸，锁屏之类）以.net framwork4，因为系统大多自带环境，而netcore不自带，且无法裁剪发布
3. 客户端和服务端都都在主程序中，服务端支持linux，而客户端暂时不支持，因为有许多功能我还暂时无法实现

**Comment by xingzuhui** [comment]
这个东西我上学的时候2007年华南理工的学校就实现了。还带我我们参观。估计是一个浪费国家经费的项目。
如果做成商业的，是不适合手机看的，这是一个现场管理的场景，像活动目录一样，但是实施控制又不同，所以定位是电子教室项目。

1.开发屏幕分享，每个人的屏幕主控都可以分享出去。标记分享的是谁的。主控可以指定被控的模式
  这里有细节，比如被分享的客户端能控制电脑，其他人看。
  主控看分享他的电脑，客户端可以分屏，被控就可以一边看一边学习主控的操作。
2.可以集成服务器的文件共享功能。主控端分享文件给指定电脑。

其实控制热键网上我也找了，但是控制ctrl+alt+del 和win+f4等，很难拿，你是怎么做到的。了解了win32太深，太累了。

**Comment by xingzuhui** [comment]
还有，市面上商业电子教室也参考一些，就跟写论文一样，要了解现状，不然做了简陋还不如成品的东西。
当然，不要全面，一面细致，一个场景解决痛点就好。不然要团队开发或者一生做一件事。

**Comment by snltty** [comment]
1、net8 用了
2、winform已经换成net8了，不过没发布单文件，需要单独安装运行环境
3、全都是64 的，没有32
现在只解决我的场景需求，其它的需求碰到了再说吧

**Comment by xingzuhui** [comment]
等你弄完，我也搞一下，有电子教师需求的，都可以用。

**Comment by snltty** [comment]
几乎弄完了，就是还有个奇异的bug，内存共享的，还在解决

**Comment by xingzuhui** [comment]
客户端安装需要系统角色，system 这个。客户端不允许管理员觉得结束进程，你看下需要实现这个。
卸载的时候需要密码，像360服务器版一样。

**Comment by sgf** [comment]
关于手机查看监控,虽然网页能看,但应该也只是能看.如果要做移动端web操作适配之类的,那估计开发代价还是相当高的.

**Comment by snltty** [comment]
@sgf 我现在用手机多，看电脑时间不多，所以先做的移动端UI，后续有时间肯定会做PC端

**Comment by snltty** [comment]
@xingzuhui 这个得了解一下怎么实现

**Comment by xingzuhui** [comment]
你是从头做的吗? 我看了源码,不堪入目啊. 怎么for循环嵌套啊,尽量不要用循环,用集合的linkq,所有实现ienumerable的都可以.
task.run了,怎么还用线程阻塞,task.run是开启多线程,让他等待,要task.delay, 我晕,我才看一眼啊.
你C#高级语法一点不懂吗?

**Comment by xingzuhui** [comment]
用wpf的化,notify这个窗体不用win32就可以实现这些效果,窗体透明阴影,还有移动是动画,简单的轨迹动画.

**Comment by xingzuhui** [comment]
好多业务代码写在窗体里,你知道我多难受啊.winform能用partial class 吗?

**Comment by xingzuhui** [comment]
if (string.IsNullOrWhiteSpace(domain)) return null;
                if (IPAddress.TryParse(domain, out IPAddress ip))
                {
                    return ip;
                }
                IPAddress[] list = Dns.GetHostEntry(domain).AddressList;
                if (list.Length > 0) return list[0];
                return null;

好像一句话就可以
return Dns.GetHostEntry(domain)?.AddressList?.First()

**Comment by snltty** [comment]
@xingzuhui  什么乱七八糟的，什么循环的linq的

**Comment by snltty** [comment]
message 是独立程序，无法mvvm传递

**Comment by xingzuhui** [comment]
不好意思,是我看错了.都没问题的.

**Comment by snltty** [comment]
有哪些循环应该用linq的你可以截图看看，我可以看看我当时怎么想的
