### ISSUE TITLE
请问组网怎么使用

### ISSUE THREAD

**Issue by parabeyond008** [snltty/cmonitor#5]
想和朋友玩对战游戏，之前用的zerotier
我下载的：network-win-x64 ，解压有2个文件夹 any、single
我不知道怎么使用这个组网程序

**Comment by snltty** [comment]
https://www.bilibili.com/video/BV11y411b7gf/

**Comment by sgf** [comment]
视频我看了，但没搞明白。up你视频里面两个都是client。
在互联网上面，不管你打不打洞，你都应该需要一个server才对啊。但是视频里面没有体现 开启server的步骤。

**Comment by snltty** [comment]
> > https://www.bilibili.com/video/BV11y411b7gf/
> 
> 视频我看了，但没搞明白。up你视频里面两个都是client。 在互联网上面，不管你打不打洞，你都应该需要一个server才对啊。但是视频里面没有体现 开启server的步骤。

我用了我自己的服务器，你可以 在 cmonnon.json 里，删除client，只保留server，就可以启动为服务端

**Comment by sgf** [comment]
> > > https://www.bilibili.com/video/BV11y411b7gf/
> > 
> > 
> > 视频我看了，但没搞明白。up你视频里面两个都是client。 在互联网上面，不管你打不打洞，你都应该需要一个server才对啊。但是视频里面没有体现 开启server的步骤。
> 
> 我用了我自己的服务器，你可以 在 cmonnon.json 里，删除client，只保留server，就可以启动为服务端

下载了最新版本,感觉都按照要求配置了.但是:

第1. 为什么1804是在客户端访问?服务端没法访问.
第2.客户端都设置好了,但是两台电脑的客户端每侧的列表中都只有自己.而服务端完全是不知道什么状况,没有任何有价值的日志.
第3.服务端server.json 生成了两个 SecretKey ,刚开始我没删.后面我就给删了. 客户端还是不行.(无法互通,准确来说是不知道怎么互通)

**Comment by snltty** [comment]
可以进群问
