### ISSUE TITLE
功能请求

### ISSUE THREAD

**Issue by chaoyi996** [snltty/cmonitor#6]
作者你好：
感谢提供优秀作品，经过试用效果良好，有一功能，不知能否加入：

端口映射时本机绑定的是any地址，这样局域网再没有防火墙策略的时候也能访问到相应的端口，能否加入一个绑定本地ip的功能，比如选择只绑定127.0.0.1地址，在企业内部和远程运维时更加方便通过攻防演练。

感谢。

**Comment by snltty** [comment]
你是说端口转发功能，添加转发那里么

**Comment by chaoyi996** [comment]
> 你是说端口转发功能，添加转发那里么

是的，目前转发到本机的端口，监听的应该是any吧。

**Comment by snltty** [comment]
对的，监听方是any，倒也是可以加个配置选项，默认0.0.0.0就行，有空我就加一下

**Comment by chaoyi996** [comment]
好的感谢

**Comment by snltty** [comment]
已更新
